services:
  db:
    container_name: postgres-15
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
    command: >
          postgres
          -c shared_preload_libraries=pglogical
          -c wal_level=logical
          -c wal_sender_timeout=0
    ports:
      - 5432:5432
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge
    name: postgres-net
